// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAEtnG1WctPP02A8KECXBX-T7wbgBqetE',
    appId: '1:493496908633:web:ba7525133c8589f4f3aa48',
    messagingSenderId: '493496908633',
    projectId: 'sacco-mobile-app',
    authDomain: 'sacco-mobile-app.firebaseapp.com',
    storageBucket: 'sacco-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Dr5fdRLOdTigYmDwzPEAfixi8Gc4xbQ',
    appId: '1:493496908633:android:39311fb711c2411ff3aa48',
    messagingSenderId: '493496908633',
    projectId: 'sacco-mobile-app',
    storageBucket: 'sacco-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6WwaKMqxgGwzMmoZ4azWX1h5PjntlynE',
    appId: '1:493496908633:ios:cd9544717f49b2b3f3aa48',
    messagingSenderId: '493496908633',
    projectId: 'sacco-mobile-app',
    storageBucket: 'sacco-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.saccoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6WwaKMqxgGwzMmoZ4azWX1h5PjntlynE',
    appId: '1:493496908633:ios:cd9544717f49b2b3f3aa48',
    messagingSenderId: '493496908633',
    projectId: 'sacco-mobile-app',
    storageBucket: 'sacco-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.saccoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAEtnG1WctPP02A8KECXBX-T7wbgBqetE',
    appId: '1:493496908633:web:6fc7558245045c4ff3aa48',
    messagingSenderId: '493496908633',
    projectId: 'sacco-mobile-app',
    authDomain: 'sacco-mobile-app.firebaseapp.com',
    storageBucket: 'sacco-mobile-app.firebasestorage.app',
  );
}
